Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    echo "10.0.30.10  prometheus00" >> /etc/hosts 
    echo "10.0.30.11  prometheus01" >> /etc/hosts 
    echo "10.0.30.12  prometheus02" >> /etc/hosts 
    echo "10.0.30.13  grafana00" >> /etc/hosts 

  SHELL

  # Grafana
  config.vm.define "grafana00" do |node|
    node.vm.box = "generic/ubuntu2010"
    node.vm.hostname = "grafana00"
    node.vm.network "private_network", ip: "10.0.30.13"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.name = "grafana00"
      vb.cpus = 1
    end
    node.vm.provision "shell", path: "scripts/add_user.sh"
  end
  
  # Cluster Prometheus
  (0..2).each do |vcont|
    config.vm.define "prometheus0#{vcont}" do |node|
      node.vm.box = "generic/ubuntu2010"
      node.vm.hostname = "prometheus0#{vcont}"
      node.vm.network "private_network", ip: "10.0.30.1#{vcont}"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.name = "prometheus-0#{vcont}"
        vb.cpus = 1
      end
      node.vm.provision "shell", path: "scripts/add_user.sh"
    end
  end
  
end
