# - name: Add the Grafana GPG key and APT repository
#   shell: |
#     curl https://packages.grafana.com/gpg.key | sudo apt-key add -
#     add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
#   args:
#     warn: no

- name: Import the grafana gpg key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  become: true

- name: Install grafana repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
  become: true

- name: Install the grafana package
  apt:
    name: grafana
    state: present
    update_cache: yes
  notify:
    - Start grafana
    - Enable grafana